import * as THREE from 'three';

const scene=new THREE.Scene();scene.background=new THREE.Color(0x07111f);scene.fog=new THREE.Fog(0x07111f,45,210);
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,500);camera.position.set(0,5.8,11);camera.lookAt(0,1, -20);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0x9bdcff,0x10151c,2.0));const sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(-20,35,20);sun.castShadow=true;scene.add(sun);

const roadW=14, segment=12, roadLen=260;let roadParts=[];
function box(w,h,d,color,x,y,z){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.8}));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m}
for(let z=-roadLen/2;z<roadLen/2;z+=segment){const r=box(roadW,.12,segment,0x20252c,0,0,z);roadParts.push(r);box(.18,.04,segment*.55,0xf3f4f6,-3.5,.09,z);box(.18,.04,segment*.55,0xf3f4f6,3.5,.09,z);box(.22,.08,segment,0xffd84a,-roadW/2-.15,.08,z);box(.22,.08,segment,0xffd84a,roadW/2+.15,.08,z)}
const ground=box(240,.2,300,0x102b1b,0,-.16,-80);
for(let i=0;i<70;i++){const side=Math.random()<.5?-1:1,x=side*(10+Math.random()*42),z=-Math.random()*230;const trunk=box(.5,2+Math.random()*3,.5,0x5a3926,x,1,z);const crown=new THREE.Mesh(new THREE.SphereGeometry(1.5+Math.random()*1.7,8,6),new THREE.MeshStandardMaterial({color:0x145b32}));crown.position.set(x,3.2,z);scene.add(crown)}
const moon=new THREE.Mesh(new THREE.SphereGeometry(7,24,16),new THREE.MeshBasicMaterial({color:0x8fb6ff}));moon.position.set(-65,50,-170);scene.add(moon);

function makeCar(color=0x00d9ff){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(2.15,.55,4.1),new THREE.MeshStandardMaterial({color,metalness:.15,roughness:.45}));body.position.y=.62;body.castShadow=true;g.add(body);const cabin=new THREE.Mesh(new THREE.BoxGeometry(1.55,.65,1.9),new THREE.MeshStandardMaterial({color:0x172b45,metalness:.1,roughness:.2}));cabin.position.set(0,1.05,.15);cabin.castShadow=true;g.add(cabin);for(const x of[-.92,.92])for(const z of[-1.35,1.35]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.38,.38,.22,16),new THREE.MeshStandardMaterial({color:0x080a0e}));w.rotation.z=Math.PI/2;w.position.set(x,.38,z);g.add(w)}const lampMat=new THREE.MeshStandardMaterial({color:0xffffff,emissive:0xaaddff,emissiveIntensity:3});for(const x of[-.65,.65]){const l=new THREE.Mesh(new THREE.BoxGeometry(.35,.15,.08),lampMat);l.position.set(x,.72,-2.07);g.add(l)}return g}
const player=makeCar(0x00d9ff);player.position.set(0,0,6);scene.add(player);
const lanes=[-5.25,-1.75,1.75,5.25],traffic=[],coins=[];let score=0,best=Number(localStorage.getItem('neon3dBest')||0),speed=28,running=false,paused=false,spawn=0,coinSpawn=0,last=0,steer=0,throttle=0;
const speedEl=document.querySelector('#speed'),scoreEl=document.querySelector('#score'),bestEl=document.querySelector('#best');bestEl.textContent=best;
function addTraffic(){const colors=[0xff3d81,0xffc928,0x9b6cff,0x25e0a0,0xff7043];const c=makeCar(colors[Math.floor(Math.random()*colors.length)]);c.position.set(lanes[Math.floor(Math.random()*lanes.length)],0,-110);c.userData.speed=15+Math.random()*15;scene.add(c);traffic.push(c)}
function addCoin(){const c=new THREE.Mesh(new THREE.TorusGeometry(.42,.12,10,18),new THREE.MeshStandardMaterial({color:0xffd23f,emissive:0x7a4d00,emissiveIntensity:1}));c.rotation.x=Math.PI/2;c.position.set(lanes[Math.floor(Math.random()*lanes.length)],1,-115);scene.add(c);coins.push(c)}
function reset(){score=0;speed=28;player.position.x=0;traffic.splice(0).forEach(x=>scene.remove(x));coins.splice(0).forEach(x=>scene.remove(x));spawn=0;coinSpawn=0;updateHud()}
function updateHud(){speedEl.textContent=Math.round(speed*3.6);scoreEl.textContent=Math.floor(score);bestEl.textContent=best}
function crash(){running=false;best=Math.max(best,Math.floor(score));localStorage.setItem('neon3dBest',best);document.querySelector('#finalScore').textContent=Math.floor(score);document.querySelector('#finalBest').textContent=best;document.querySelector('#over').classList.remove('hidden');updateHud()}
function start(){reset();running=true;paused=false;document.querySelector('#menu').classList.add('hidden');document.querySelector('#over').classList.add('hidden');document.querySelector('#pause').classList.add('hidden');last=performance.now();requestAnimationFrame(loop)}
function pause(){if(!running)return;paused=!paused;document.querySelector('#pause').classList.toggle('hidden',!paused);if(!paused){last=performance.now();requestAnimationFrame(loop)}}
function key(e,on){const k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown','a','d','w','s',' '].includes(k))e.preventDefault();if(k==='arrowleft'||k==='a')steer=on?-1:0;if(k==='arrowright'||k==='d')steer=on?1:0;if(k==='arrowup'||k==='w')throttle=on?1:0;if(k==='arrowdown'||k==='s')throttle=on?-1:0;if(k===' '&&on)pause()}
addEventListener('keydown',e=>key(e,true));addEventListener('keyup',e=>key(e,false));
function bind(id,fn){const b=document.querySelector(id);b.addEventListener('pointerdown',e=>{e.preventDefault();fn(true)});b.addEventListener('pointerup',e=>{e.preventDefault();fn(false)});b.addEventListener('pointerleave',e=>fn(false))}bind('#left',v=>steer=v?-1:0);bind('#right',v=>steer=v?1:0);bind('#boost',v=>throttle=v?1:0);bind('#brake',v=>throttle=v?-1:0);
document.querySelector('#start').onclick=start;document.querySelector('#again').onclick=start;document.querySelector('#resume').onclick=pause;
function loop(t){if(!running||paused)return;const dt=Math.min((t-last)/1000,.04);last=t;speed+=dt*(1.8+score/4000);if(throttle>0)speed+=dt*15;if(throttle<0)speed-=dt*24;speed=THREE.MathUtils.clamp(speed,18,72);score+=dt*speed*.75;
player.position.x+=steer*dt*8;player.position.x=THREE.MathUtils.clamp(player.position.x,-6.1,6.1);player.rotation.z=-steer*.08;camera.position.x+=(player.position.x*.18-camera.position.x)*dt*3;camera.lookAt(player.position.x*.1,1,-22);
spawn-=dt;coinSpawn-=dt;if(spawn<=0){addTraffic();spawn=Math.max(.45,1.15-score/18000)}if(coinSpawn<=0){addCoin();coinSpawn=.7+Math.random()*1.1}
for(let i=traffic.length-1;i>=0;i--){const c=traffic[i];c.position.z+=(speed-c.userData.speed)*dt;if(c.position.z>18){scene.remove(c);traffic.splice(i,1);continue}if(Math.abs(c.position.x-player.position.x)<1.65&&Math.abs(c.position.z-player.position.z)<2.7){crash();return}}
for(let i=coins.length-1;i>=0;i--){const c=coins[i];c.position.z+=speed*dt;c.rotation.z+=dt*5;if(c.position.z>18){scene.remove(c);coins.splice(i,1);continue}if(Math.abs(c.position.x-player.position.x)<1.4&&Math.abs(c.position.z-player.position.z)<2.4){score+=100;scene.remove(c);coins.splice(i,1)}}
for(const r of roadParts){r.position.z+=speed*dt;if(r.position.z>18)r.position.z-=roadLen}updateHud();renderer.render(scene,camera);requestAnimationFrame(loop)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});renderer.render(scene,camera);
